name: Update Welo Reviews

on:
  workflow_dispatch:   # lo puoi avviare anche a mano
  schedule:
    - cron: "0 0 * * *"   # ogni giorno alle 00:00 (timezone Rome)

env:
  TZ: Europe/Rome     # forza il fuso orario italiano

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci || npm i

      - name: Fetch Webflow CMS data
        env:
          WEBFLOW_TOKEN: ${{ secrets.WEBFLOW_TOKEN }}
          WEBFLOW_COLLECTION_ID: 674d7153240404723fc12f5a
          WEBFLOW_ITEM_SLUG: welo
        run: node fetch.js

      - name: Commit and push data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Daily update"
          file_pattern: data/*.json
